### ISSUE TITLE
Non-compatibility of cnes-pylint-extension version 6 with pylint version 3

### ISSUE THREAD

**Issue by devigno** [cnescatlab/cnes-pylint-extension#16]
We are using version 6 of cnes-pylint-extension on the Hysope 2 project.
We would now like to upgrade to version 3 of pylint. At the moment, this is not compatible with the current version of the extension. 

Are there any plans to release a new version of this extension and when?

Pending your reply, we are going to deactivate this extension and migrate to pylint vesrion 3, in order to benefit from the most recent pylint improvements.

**Comment by louisjdmartin** [comment]
Hi @devigno 
We just pushed the release candidate for compatibility with pylint 3.0, check it at: https://pypi.org/project/cnes-pylint-extension/7.0.0rc1/

```pip install cnes-pylint-extension==7.0.0rc1```

As this update introduce some breaking changes, we want to be sure that everything works perfectly before pushing as stable. If you try this version and find bugs don't hesitate to open a new issue.
